[2022-04-06 17:50:11,118] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: send_mail.sendmail scheduled__2022-04-06T17:48:08.695987+00:00 [queued]>
[2022-04-06 17:50:11,130] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: send_mail.sendmail scheduled__2022-04-06T17:48:08.695987+00:00 [queued]>
[2022-04-06 17:50:11,130] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-06 17:50:11,131] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-06 17:50:11,131] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-06 17:50:11,145] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): sendmail> on 2022-04-06 17:48:08.695987+00:00
[2022-04-06 17:50:11,149] {standard_task_runner.py:52} INFO - Started process 1766 to run task
[2022-04-06 17:50:11,152] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'send_mail', 'sendmail', 'scheduled__2022-04-06T17:48:08.695987+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/send_mail_dag.py', '--cfg-path', '/tmp/tmpvtk8dn6o', '--error-file', '/tmp/tmpuyry1ete']
[2022-04-06 17:50:11,152] {standard_task_runner.py:80} INFO - Job 18: Subtask sendmail
[2022-04-06 17:50:11,210] {logging_mixin.py:109} INFO - Running <TaskInstance: send_mail.sendmail scheduled__2022-04-06T17:48:08.695987+00:00 [running]> on host 669712b97f52
[2022-04-06 17:50:11,261] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=send_mail
AIRFLOW_CTX_TASK_ID=sendmail
AIRFLOW_CTX_EXECUTION_DATE=2022-04-06T17:48:08.695987+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-06T17:48:08.695987+00:00
[2022-04-06 17:50:13,171] {logging_mixin.py:109} INFO - Something went wrongâ€¦. (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials l10-20020a056a00140a00b004c55d0dcbd1sm20063439pfu.120 - gsmtp')
[2022-04-06 17:50:13,171] {python.py:175} INFO - Done. Returned value was: None
[2022-04-06 17:50:13,184] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=send_mail, task_id=sendmail, execution_date=20220406T174808, start_date=20220406T175011, end_date=20220406T175013
[2022-04-06 17:50:13,208] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-06 17:50:13,239] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
