[2022-04-06 17:37:41,700] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: send_mail.sendmail manual__2022-04-06T17:37:40.846400+00:00 [queued]>
[2022-04-06 17:37:41,711] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: send_mail.sendmail manual__2022-04-06T17:37:40.846400+00:00 [queued]>
[2022-04-06 17:37:41,711] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-06 17:37:41,711] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-06 17:37:41,711] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-06 17:37:41,722] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): sendmail> on 2022-04-06 17:37:40.846400+00:00
[2022-04-06 17:37:41,726] {standard_task_runner.py:52} INFO - Started process 1221 to run task
[2022-04-06 17:37:41,729] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'send_mail', 'sendmail', 'manual__2022-04-06T17:37:40.846400+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/send_mail_dag.py', '--cfg-path', '/tmp/tmpo_9fah0g', '--error-file', '/tmp/tmpf_y_v3k9']
[2022-04-06 17:37:41,729] {standard_task_runner.py:80} INFO - Job 16: Subtask sendmail
[2022-04-06 17:37:41,783] {logging_mixin.py:109} INFO - Running <TaskInstance: send_mail.sendmail manual__2022-04-06T17:37:40.846400+00:00 [running]> on host 669712b97f52
[2022-04-06 17:37:41,858] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=send_mail
AIRFLOW_CTX_TASK_ID=sendmail
AIRFLOW_CTX_EXECUTION_DATE=2022-04-06T17:37:40.846400+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-06T17:37:40.846400+00:00
[2022-04-06 17:37:43,642] {logging_mixin.py:109} INFO - Something went wrongâ€¦. (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials e13-20020a63370d000000b003810782e0cdsm16781023pga.56 - gsmtp')
[2022-04-06 17:37:43,642] {python.py:175} INFO - Done. Returned value was: None
[2022-04-06 17:37:43,661] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=send_mail, task_id=sendmail, execution_date=20220406T173740, start_date=20220406T173741, end_date=20220406T173743
[2022-04-06 17:37:43,704] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-06 17:37:43,745] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
