[2022-04-06 17:37:32,470] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: send_mail.sendmail scheduled__2022-04-06T17:35:18.849348+00:00 [queued]>
[2022-04-06 17:37:32,482] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: send_mail.sendmail scheduled__2022-04-06T17:35:18.849348+00:00 [queued]>
[2022-04-06 17:37:32,482] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-06 17:37:32,482] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-06 17:37:32,482] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-06 17:37:32,493] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): sendmail> on 2022-04-06 17:35:18.849348+00:00
[2022-04-06 17:37:32,498] {standard_task_runner.py:52} INFO - Started process 1219 to run task
[2022-04-06 17:37:32,501] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'send_mail', 'sendmail', 'scheduled__2022-04-06T17:35:18.849348+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/send_mail_dag.py', '--cfg-path', '/tmp/tmpinq2l356', '--error-file', '/tmp/tmpvmi36aqg']
[2022-04-06 17:37:32,501] {standard_task_runner.py:80} INFO - Job 15: Subtask sendmail
[2022-04-06 17:37:32,565] {logging_mixin.py:109} INFO - Running <TaskInstance: send_mail.sendmail scheduled__2022-04-06T17:35:18.849348+00:00 [running]> on host 669712b97f52
[2022-04-06 17:37:32,617] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=send_mail
AIRFLOW_CTX_TASK_ID=sendmail
AIRFLOW_CTX_EXECUTION_DATE=2022-04-06T17:35:18.849348+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-06T17:35:18.849348+00:00
[2022-04-06 17:37:34,997] {logging_mixin.py:109} INFO - Something went wrongâ€¦. (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials u12-20020a17090a890c00b001b8efcf8e48sm6197576pjn.14 - gsmtp')
[2022-04-06 17:37:34,997] {python.py:175} INFO - Done. Returned value was: None
[2022-04-06 17:37:35,018] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=send_mail, task_id=sendmail, execution_date=20220406T173518, start_date=20220406T173732, end_date=20220406T173735
[2022-04-06 17:37:35,082] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-06 17:37:35,125] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
