[2022-04-06 17:22:56,147] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: send_mail.sendmail scheduled__2022-04-06T17:20:54.751808+00:00 [queued]>
[2022-04-06 17:22:56,158] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: send_mail.sendmail scheduled__2022-04-06T17:20:54.751808+00:00 [queued]>
[2022-04-06 17:22:56,158] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-06 17:22:56,158] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-06 17:22:56,158] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-06 17:22:56,170] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): sendmail> on 2022-04-06 17:20:54.751808+00:00
[2022-04-06 17:22:56,174] {standard_task_runner.py:52} INFO - Started process 580 to run task
[2022-04-06 17:22:56,177] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'send_mail', 'sendmail', 'scheduled__2022-04-06T17:20:54.751808+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/send_mail_dag.py', '--cfg-path', '/tmp/tmpm5yfcrgn', '--error-file', '/tmp/tmpo2j7stv6']
[2022-04-06 17:22:56,177] {standard_task_runner.py:80} INFO - Job 9: Subtask sendmail
[2022-04-06 17:22:56,231] {logging_mixin.py:109} INFO - Running <TaskInstance: send_mail.sendmail scheduled__2022-04-06T17:20:54.751808+00:00 [running]> on host 669712b97f52
[2022-04-06 17:22:56,281] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=send_mail
AIRFLOW_CTX_TASK_ID=sendmail
AIRFLOW_CTX_EXECUTION_DATE=2022-04-06T17:20:54.751808+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-06T17:20:54.751808+00:00
[2022-04-06 17:22:58,638] {logging_mixin.py:109} INFO - Something went wrongâ€¦. (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials l13-20020a056a00140d00b004e13da93eaasm19857962pfu.62 - gsmtp')
[2022-04-06 17:22:58,639] {python.py:175} INFO - Done. Returned value was: None
[2022-04-06 17:22:58,677] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=send_mail, task_id=sendmail, execution_date=20220406T172054, start_date=20220406T172256, end_date=20220406T172258
[2022-04-06 17:22:58,718] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-06 17:22:58,745] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
