[2022-04-06 17:21:17,084] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: send_mail.sendmail manual__2022-04-06T17:21:15.742596+00:00 [queued]>
[2022-04-06 17:21:17,102] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: send_mail.sendmail manual__2022-04-06T17:21:15.742596+00:00 [queued]>
[2022-04-06 17:21:17,103] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-06 17:21:17,103] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-06 17:21:17,103] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-06 17:21:17,118] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): sendmail> on 2022-04-06 17:21:15.742596+00:00
[2022-04-06 17:21:17,123] {standard_task_runner.py:52} INFO - Started process 503 to run task
[2022-04-06 17:21:17,128] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'send_mail', 'sendmail', 'manual__2022-04-06T17:21:15.742596+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/send_mail_dag.py', '--cfg-path', '/tmp/tmpkc8dkr8w', '--error-file', '/tmp/tmp1t8j7bh0']
[2022-04-06 17:21:17,128] {standard_task_runner.py:80} INFO - Job 7: Subtask sendmail
[2022-04-06 17:21:17,194] {logging_mixin.py:109} INFO - Running <TaskInstance: send_mail.sendmail manual__2022-04-06T17:21:15.742596+00:00 [running]> on host 669712b97f52
[2022-04-06 17:21:17,255] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=send_mail
AIRFLOW_CTX_TASK_ID=sendmail
AIRFLOW_CTX_EXECUTION_DATE=2022-04-06T17:21:15.742596+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-06T17:21:15.742596+00:00
[2022-04-06 17:21:19,207] {logging_mixin.py:109} INFO - Something went wrongâ€¦. (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials lj7-20020a17090b344700b001c7032eba5fsm6403279pjb.4 - gsmtp')
[2022-04-06 17:21:19,207] {python.py:175} INFO - Done. Returned value was: None
[2022-04-06 17:21:19,220] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=send_mail, task_id=sendmail, execution_date=20220406T172115, start_date=20220406T172117, end_date=20220406T172119
[2022-04-06 17:21:19,266] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-06 17:21:19,297] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
